"""add label id to user

Revision ID: 089118f221b3
Revises: 979b72f11858
Create Date: 2024-07-25 08:26:25.450293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089118f221b3'
down_revision: Union[str, None] = '979b72f11858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cleanmail_label_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cleanmail_label_id')
    # ### end Alembic commands ###
