"""Add query_text to GrantSearchQuery

Revision ID: 0d2acc6f9384
Revises: a420e291d3e2
Create Date: 2024-11-25 21:03:53.341230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2acc6f9384'
down_revision: Union[str, None] = 'a420e291d3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant_search_queries', sa.Column('query_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grant_search_queries', 'query_text')
    # ### end Alembic commands ###
