"""adds sender_address index

Revision ID: 3a8f2306646a
Revises: 55150c564d5f
Create Date: 2024-07-03 15:15:12.571719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8f2306646a'
down_revision: Union[str, None] = '55150c564d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_gmail_sender_addresses_sender_id', 'gmail_sender_address', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_gmail_sender_addresses_sender_id', table_name='gmail_sender_address')
    # ### end Alembic commands ###
