"""Add timestamps

Revision ID: 415d17c9acba
Revises: 9e8017b537c3
Create Date: 2024-11-25 15:53:29.555720

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "415d17c9acba"
down_revision: Union[str, None] = "9e8017b537c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("grant_search_queries", sa.Column("created_at", sa.DateTime()))
    op.add_column("grant_search_queries", sa.Column("last_modified", sa.DateTime()))

    # Set default values for existing rows
    op.execute(
        "UPDATE grant_search_queries SET created_at = NOW(), last_modified = NOW()"
    )

    # Make columns non-nullable after setting defaults
    op.alter_column("grant_search_queries", "created_at", nullable=False)
    op.alter_column("grant_search_queries", "last_modified", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("grant_search_queries", "last_modified")
    op.drop_column("grant_search_queries", "created_at")
    # ### end Alembic commands ###
