"""add grant summary

Revision ID: 46c047a5d2e6
Revises: 2796a449b927
Create Date: 2025-01-02 14:18:21.257311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c047a5d2e6'
down_revision: Union[str, None] = '2796a449b927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant_derived_data', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grant_derived_data', 'summary')
    # ### end Alembic commands ###
