"""makes user email unique

Revision ID: 55150c564d5f
Revises: 94a4214b0f54
Create Date: 2024-07-02 17:18:53.526467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55150c564d5f'
down_revision: Union[str, None] = '94a4214b0f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_google_user_email', 'users', ['email'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('idx_google_user_email', table_name='users')
    # ### end Alembic commands ###
