"""Adds sender status

Revision ID: 570c01eb7a46
Revises: 3a8f2306646a
Create Date: 2024-07-08 10:14:48.274134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570c01eb7a46'
down_revision: Union[str, None] = '3a8f2306646a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_sender', sa.Column('status', sa.Enum('NONE', 'CLEAN', 'KEEP', 'LATER', name='senderstatus'), nullable=True))
    op.drop_column('gmail_sender', 'should_be_cleaned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_sender', sa.Column('should_be_cleaned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('gmail_sender', 'status')
    # ### end Alembic commands ###
