"""Add users and favorites

Revision ID: 6188e173690f
Revises: 0d2acc6f9384
Create Date: 2024-12-12 22:28:17.016648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6188e173690f'
down_revision: Union[str, None] = '0d2acc6f9384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grant_derived_dataX')
    op.add_column('grant_search_queries', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grant_search_queries', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('last_modified', sa.DateTime(), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'last_modified')
    op.drop_constraint(None, 'grant_search_queries', type_='foreignkey')
    op.drop_column('grant_search_queries', 'user_id')
    op.create_table('grant_derived_dataX',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dei_status', postgresql.ENUM('NONE', 'MENTIONS_DEI', 'PARTIAL_DEI', 'PRIMARILY_DEI', name='deistatus'), autoincrement=False, nullable=True),
    sa.Column('dei_women', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dei_race', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('outrageous', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('primary_dei', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hard_science', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('political_science', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('carbon', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], name='grant_derived_dataX_grant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='grant_derived_dataX_pkey')
    )
    # ### end Alembic commands ###
