"""Add is_cleaining to user status

Revision ID: 7817de4e6ef6
Revises: aefbff9fd0cd
Create Date: 2024-07-01 17:00:58.455463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7817de4e6ef6'
down_revision: Union[str, None] = 'aefbff9fd0cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_status', sa.Column('is_cleaning', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_status', 'is_cleaning')
    # ### end Alembic commands ###
