"""Create QuerySearch2

Revision ID: 7cd6737c8b34
Revises: 78fecbb5fa19
Create Date: 2024-11-25 11:00:27.920775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd6737c8b34'
down_revision: Union[str, None] = '78fecbb5fa19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grant_search_query_grants',
    sa.Column('grant_search_query_id', sa.Integer(), nullable=True),
    sa.Column('grant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ),
    sa.ForeignKeyConstraint(['grant_search_query_id'], ['grant_search_queries.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grant_search_query_grants')
    # ### end Alembic commands ###
