"""Add cleaning_start

Revision ID: 94a4214b0f54
Revises: 7817de4e6ef6
Create Date: 2024-07-01 17:01:47.477288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a4214b0f54'
down_revision: Union[str, None] = '7817de4e6ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_status', sa.Column('cleaning_start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_status', 'cleaning_start')
    # ### end Alembic commands ###
