"""Adds email status counts

Revision ID: 979b72f11858
Revises: 570c01eb7a46
Create Date: 2024-07-08 14:58:21.643424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979b72f11858'
down_revision: Union[str, None] = '570c01eb7a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_status', sa.Column('email_count', sa.Integer(), nullable=True))
    op.add_column('user_status', sa.Column('deleted_emails', sa.Integer(), nullable=True))
    op.add_column('user_status', sa.Column('to_be_deleted_emails', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_status', 'to_be_deleted_emails')
    op.drop_column('user_status', 'deleted_emails')
    op.drop_column('user_status', 'email_count')
    # ### end Alembic commands ###
