"""Use Stats type

Revision ID: 9a41c358a92f
Revises: 089118f221b3
Create Date: 2024-07-25 13:02:18.696573

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from cleanmail.db.models import AddressStatsType


# revision identifiers, used by Alembic.
revision: str = "9a41c358a92f"
down_revision: Union[str, None] = "089118f221b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("gmail_sender", sa.Column("stats", AddressStatsType(), nullable=True))
    op.drop_column("gmail_sender", "emails_unread")
    op.drop_column("gmail_sender", "emails_sent")
    op.drop_column("gmail_sender", "emails_deleted")
    op.drop_column("gmail_sender", "emails_replied")
    op.drop_column("gmail_sender", "emails_important")
    op.add_column(
        "gmail_sender_address", sa.Column("stats", AddressStatsType(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gmail_sender_address", "stats")
    op.add_column(
        "gmail_sender",
        sa.Column("emails_important", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "gmail_sender",
        sa.Column("emails_replied", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "gmail_sender",
        sa.Column("emails_deleted", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "gmail_sender",
        sa.Column("emails_sent", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "gmail_sender",
        sa.Column("emails_unread", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("gmail_sender", "stats")
    # ### end Alembic commands ###
