"""Create add sampling fraction

Revision ID: 9e8017b537c3
Revises: 7cd6737c8b34
Create Date: 2024-11-25 13:17:26.924711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8017b537c3'
down_revision: Union[str, None] = '7cd6737c8b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant_search_queries', sa.Column('sampling_fraction', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grant_search_queries', 'sampling_fraction')
    # ### end Alembic commands ###
