"""Add status to query

Revision ID: a420e291d3e2
Revises: 415d17c9acba
Create Date: 2024-11-25 16:16:03.659222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a420e291d3e2'
down_revision: Union[str, None] = '415d17c9acba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant_search_queries', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grant_search_queries', 'status')
    # ### end Alembic commands ###
