"""Add to_be_cleaned in sender

Revision ID: aefbff9fd0cd
Revises: c01c320061d5
Create Date: 2024-07-01 16:47:10.432524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aefbff9fd0cd'
down_revision: Union[str, None] = 'c01c320061d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_sender', sa.Column('emails_deleted', sa.Integer(), nullable=True))
    op.add_column('gmail_sender', sa.Column('should_be_cleaned', sa.Boolean(), nullable=True))
    op.add_column('gmail_sender', sa.Column('last_cleaned', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmail_sender', 'last_cleaned')
    op.drop_column('gmail_sender', 'should_be_cleaned')
    op.drop_column('gmail_sender', 'emails_deleted')
    # ### end Alembic commands ###
