"""Add deleted

Revision ID: c01c320061d5
Revises: cd3a7add8f6a
Create Date: 2024-07-01 15:05:39.871619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01c320061d5'
down_revision: Union[str, None] = 'cd3a7add8f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_thread', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmail_thread', 'deleted')
    # ### end Alembic commands ###
