"""adds sender stats

Revision ID: cd3a7add8f6a
Revises: d78268be6171
Create Date: 2024-06-27 15:05:27.902797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3a7add8f6a'
down_revision: Union[str, None] = 'd78268be6171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_sender', sa.Column('emails_sent', sa.Integer(), nullable=True))
    op.add_column('gmail_sender', sa.Column('emails_unread', sa.Integer(), nullable=True))
    op.add_column('gmail_sender', sa.Column('emails_important', sa.Integer(), nullable=True))
    op.add_column('gmail_sender', sa.Column('emails_replied', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmail_sender', 'emails_replied')
    op.drop_column('gmail_sender', 'emails_important')
    op.drop_column('gmail_sender', 'emails_unread')
    op.drop_column('gmail_sender', 'emails_sent')
    # ### end Alembic commands ###
