"""add emails_sent back

Revision ID: eae5b3b84b6d
Revises: 9a41c358a92f
Create Date: 2024-07-25 13:48:44.701079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae5b3b84b6d'
down_revision: Union[str, None] = '9a41c358a92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_sender', sa.Column('emails_sent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmail_sender', 'emails_sent')
    # ### end Alembic commands ###
